### ISSUE TITLE
[dev] Checklist mise en place

### ISSUE THREAD

**Issue by statnmap** [ThinkR-open/example.auto#2]
- [ ] Remplir les Key Dates et le calendrier prévisionnel
- [ ] Ajouter chaque utilisateur au projet en tant que "Guest"
- [ ] Prévenir les chefs de projets de monter le niveau de Notification à "Watch" sur la page d'acceuil du projet pour recevoir toutes les notifications
- [ ] S'assurer que le Board est pret:https://github.com/ThinkR-open/example.auto/projects/1
- [ ] S'assurer que le Wiki Home est pret:https://github.com/ThinkR-open/example.auto/wiki/Home
- [ ] Indiquer aussi la méthode de partage de CR dans l'issue de Bienvenue du Client : https://github.com/ThinkR-open/example.auto/issues/1
- [ ] Notifier chaque utilisateur en les mentionnant dans un commentaire de l'issue : https://github.com/ThinkR-open/example.auto/issues/1 avec le texte suivant : 
```
Merci de bien vouloir lire et valider le contenu de cette page.
Si vous lisez ce message dans un email, vous pouvez cliquer sur le lien suivant pour accéder à la page :
https://github.com/ThinkR-open/example.auto/issues/1
@mention, @mention, ...
```

- [ ] Mettre en place {renv} en suivant "dev/dev_history_renv.R"
- [ ] Si nécessaires, exécuter les étapes de "dev/dev_history.R". La plupart sont déja faites.
